### ISSUE TITLE
linux-x86_64 compile does not compile the native gcc/binutils

### ISSUE THREAD

**Issue by alb42** [deadw00d/AROS#8]
following the build instruction
https://github.com/deadw00d/AROS/blob/master/INSTALL.md

but it does not build and install the native gcc/binutils, especially I'm interested in as, ld, collect-aros (needed for FPC)

(In the past I always used the pc-x86_64 compilation, but this doesn't compile currently)

**Comment by deadw00d** [comment]
Hi Marcus,

A few questions:
1) by native you mean gcc/binutils running under AROS, correct?
2) are you looking for ABIv0 i386 or for my stabilized ABIv1 x86-64? (different than main AROS x86_64 which has not stable ABI)

**Comment by alb42** [comment]
hi deadwood,

1) yes. I want to run FPC (and maybe also gcc) directly under AROS

2a) no I'm looking for ABIv1 x86_64 especially your stabilized one (I always call it NonSMP) atm. because it is compatible with the one I'm use to and done the FPC port already long time before. All my programs are for that kind of x86_64-AROS and I even did a distribution https://blog.alb42.de/the-100-useless-aros-distribution/

2b) the main 64Bit AROS (I call it SMP 64-Bit AROS) did a very big change which changes the size of MsgPorts (even when compiled without SMP) making all programs crash. I asked about a working native gcc (which I need to compare structure sizes https://github.com/alb42/fpcamigachk ) but they are not willing or able to supply such thing.

2c) Later I plan to support both "flavors" of 64bit-AROS (switchable via define)

**Comment by deadw00d** [comment]
Thanks, I understand now.

After you follow INSTALL.md file, you will get "basic" AROS hosted. Next clone the contrib repository (https://github.com/deadw00d/contrib), copy it into AROS source tree, cd into core-linux-x86_64-d and invoke make contrib. You should end up with native gcc/binutils in SYS:Developer/bin (tested this just now and worked for me)

**Comment by alb42** [comment]
thanks, it doesn't work that way
it seems you have to have the contrib folder already there when calling ./configure (inside rebuild.sh) but I deleted everything and started over, added the contrib before starting the rebuild.sh. And finally I got it, sadly the collect-aros here also crash (more or less the same as in the SMP AROS :( but I remember there you could at least start it without any options and it will show a guru window, here just a trap and freeze whole AROS)
reproduce:
- open new shell
- collect-aros

[Bootstrap] Entering kernel at 0x41235000...
[KRN] Protecting host process stack (0x00007fff49619c00 - 0x00007fff49623c00)
[KRN] Trap signal 11, SysBase 00000000424b6820, KernelBase 00000000424b7a08
    RSP=00000000431b6eb8  RBP=00000000431b6fe8  RIP=00007fbd79bb2eae
    RAX=0000000000000000  RBX=0000000042fecfc8  RCX=0000000042f905c0  RDX=0000000041240929
    RDI=000000000000000a  RSI=00000000424b7a08  RFLAGS=0000000000010246
    R8 =000000000000000a  R9 =00000000431b6eb8  R10=0000000000000008  R11=0000000042ee2430
    R12=0000000000000000  R13=0000000000000000  R14=0000000000000000  R15=0000000000000000

**Comment by deadw00d** [comment]
Ok, let me have a look at this. What parameters do you want to eventually run collect-aros with?

**Comment by alb42** [comment]
for a hello world it look like this:

collect-aros  --gc-sections -e _start -d -n -o HelloWorld HelloWorld_link.res

see attached file


[HelloWorld_linkerscript.zip](https://github.com/deadw00d/AROS/files/4908636/HelloWorld_linkerscript.zip)

**Comment by deadw00d** [comment]
Thanks, I'll update this bug report when I find something.

**Comment by deadw00d** [comment]
I pushed a fix, please try. After you update AROS repo, do:

make compiler-posixc-quick

This should re-build your posixc.library where to bug was - lack of stack alignment in vfork()

**Comment by alb42** [comment]
thanks it works ;) very nicely

The compiler works now as it should be, the FPC-IDE is still crashing, still some problems in my programs  the FP-IDE does crash on compile, icons are broken, starting from icon results in some problems and so on. But not too bad for now.

![AROS64-ALB](https://user-images.githubusercontent.com/8577668/87569213-12894900-c6c7-11ea-8264-af9ef7c6d38e.png)

Thanks for your help.
